const actionTypes = {
    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',
    FILTER_TABLE_SUCCESS: 'FILTER_TABLE_SUCCESS',
    FILTER_TABLE_START: 'FILTER_TABLE_START'
}

export default actionTypes