const actionTypes = {
    FETCH_ORDERS_START: 'FETCH_ORDERS_START',
    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',
    FILTER_TABLE_SUCCESS: 'FILTER_TABLE_SUCCESS'
}

export default actionTypes