const actionTypes = {
    SET_SHOW_SUCCESS:'SET_SHOW_SUCCESS',
    FETCH_TAXIMETERS_FAILURE:'FETCH_TAXIMETERS_FAILURE',
    FETCH_TAXIMETERS_SUCCESS:'FETCH_TAXIMETERS_SUCCESS',
    POST_TAXIMETER_SUCCESS:'POST_TAXIMETER_SUCCESS',
    POST_TAXIMETER_FAILURE:'POST_TAXIMETER_FAILURE',
    UPDATE_TAXIMETER_SUCCESS:'UPDATE_TAXIMETER_SUCCESS',
    UPDATE_TAXIMETER_FAILURE:'UPDATE_TAXIMETER_FAILURE',
    DELETE_TAXIMETER_SUCCESS:'DELETE_TAXIMETER_SUCCESS',
    DELETE_TAXIMETER_FAILURE:'DELETE_TAXIMETER_FAILURE',
    GET_VERIFICATION_SUCCESS: 'GET_VERIFICATION_SUCCESS',
    GET_VERIFICATION_FAILURE: 'GET_VERIFICATION_FAILURE',
}
export default actionTypes