const actionTypes = {
    SET_SHOW_SUCCESS: 'SET_SHOW_SUCCESS',
    START_ORDER_FETCH: 'START_ORDER_FETCH',
    SUCCESS_ORDER_FETCH: 'SUCCESS_ORDER_FETCH',
    FAILURE_ORDER_FETCH: 'FAILURE_ORDER_FETCH',
    DELETE_PENDING_ORDERS: 'DELETE_PENDING_ORDERS'
}

export default actionTypes