const actionTypes = {
    SET_SHOW_SUCCESS: 'SET_SHOW_SUCCESS',
    START_ORDER_FETCH: 'START_ORDER_FETCH',
    SUCCESS_ORDER_FETCH: 'SUCCESS_ORDER_FETCH',
    FAILURE_ORDER_FETCH: 'FAILURE_ORDER_FETCH',
    DELETE_PENDING_ORDERS: 'DELETE_PENDING_ORDERS',
    FAILURE_DELETE_PENDING_ORDERS: 'FAILURE_DELETE_PENDING_ORDERS',
    SUCCESS_FETCH_PENDING_ORDERS: 'SUCCESS_FETCH_PENDING_ORDERS',
    FAILURE_FETCH_PENDING_ORDERS: 'FAILURE_FETCH_PENDING_ORDERS',
    DRIVER_CHANGE_FAILURE:'DRIVER_CHANGE_FAILURE',
    FILTER_TABLE_SUCCESS: 'FILTER_TABLE_SUCCESS'
}

export default actionTypes