const actionTypes = {
    SET_PHONE: 'SET_PHONE',
    SET_FROM_ADDRESS: 'SET_FROM_ADDRESS',
    SET_TO_ADDRESS: 'SET_TO_ADDRESS',
    ADD_EMPTY_INPUT: 'ADD_EMPTY_INPUT',
    RESET_ORDER: 'RESET_ORDER',
    SET_TOUCH_PHONE: 'SET_TOUCH_PHONE',
    SET_ADDITIONAL_ADDRESSES: 'SET_ADDITIONAL_ADDRESSES',
    DELETE_ADDRESS: 'DELETE_ADDRESS',
    START_ORDER_FETCH: 'START_ORDER_FETCH',
    SUCCESS_ORDER_FETCH: 'SUCCESS_ORDER_FETCH',
    FAILURE_ORDER_FETCH: 'FAILURE_ORDER_FETCH'
}

export default actionTypes